logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: ./logs/application.log
      archivedLogFilenamePattern: ./logs/application-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
      timeZone: UTC
      logFormat: "[%d{HH:mm:ss.SSS}][%-5level] %logger{36} - %msg%n"
server:
  applicationConnectors:
    - type: http
      port: 8080  # Port number, verify if set correctly
  adminConnectors:
    - type: http
      port: 8081  # Admin port, optional
database:
  dialect: org.hibernate.dialect.MySQL8Dialect
  url: jdbc:mysql://localhost:3306/PersonalFinance_database
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: Shiv@123
